List repos = [
    'home-assistant-config',
    'jenkins',
    'server-management'
]

node ('built-in') {
    for (String repo in repos) {
        dir (repo) {
            git url: "https://github.com/mfugate1/${repo}.git", branch: 'main'
        }
    }

    reloadAzureKeyVaultCache()

    jobDsl (
        targets: '**/jobConfig.groovy',
        removedJobAction: 'DELETE',
        lookupStrategy: 'SEED_JOB'
    )
}