jenkins:
  slaveAgentPort: 50000
  systemMessage: Overlord Jenkins
  numExecutors: 1
  quietPeriod: 0
  mode: NORMAL
  agentProtocols:
    - JNLP4-connect
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS-USERNAME}
          password: ${JENKINS-PASSWORD}
  globalNodeProperties:
    - envVars:
        env:
          - key: DOCKER1_REMOTE_USER
            value: jenkins
          - key: HASS_CONFIG_DIR
            value: /docker/home-assistant
          - key: HASS_TEST_CONFIG_DIR
            value: /docker/home-assistant-test
          - key: JENKINS_SSH_KEY
            value: jenkins-ssh
credentials:
  system:
    domainCredentials:
      - credentials:
        - azure:
            azureEnvironmentName: Azure
            clientId: ${AZURE_CLIENT_ID}
            clientSecret: ${AZURE_CLIENT_SECRET}
            subscriptionId: ${AZURE_SUBSCRIPTION_ID}
            tenant: ${AZURE_TENANT}
            id: az-vault
            scope: GLOBAL
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
unclassified:
  azureKeyVault:
    keyVaultURL: ${AZ_VAULT_URL}
    credentialID: az-vault
  buildDiscarders:
    configuredBuildDiscarders:
      - jobBuildDiscarder
      - defaultBuildDiscarder:
          discarder:
            logRotator:
              numToKeepStr: "10"
  globalLibraries:
    libraries:
      - name: 'jenkins-shared-library'
        defaultVersion: 'main'
        implicit: true
        includeInChangesets: false
        retriever:
          modernSCM:
            scm:
              git:
                remote: https://github.com/mfugate1/jenkins.git
  location:
    adminAddress: ${JENKINS-ADMIN-EMAIL}
    url: http://${TRUENAS-DOCKER-IP}:${JENKINS-PORT}
