jenkins:
  slaveAgentPort: 50000
  systemMessage: Overlord Jenkins
  numExecutors: 0
  quietPeriod: 0
  mode: EXCLUSIVE
  agentProtocols:
    - JNLP4-connect
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: mfugate
          password: ${JENKINS_PASSWORD}
  primaryView:
    all:
      name: All
  views:
    - list:
        columns:
          - status
          - weather
          - jobName
          - lastSuccess
          - lastFailure
          - lastDuration
          - buildButton
        jobNames:
          - Job-DSL-Runner
          - Update-Jenkins
        name: Jenkins Management
  clouds:
  - docker:
      containerCap: 1
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: unix:///var/run/docker.sock
        readTimeout: 60
      name: docker
      templates:
      - connector: attach
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: mfugate/jenkins-worker:latest
        labelString: "python3 chrome selenium docker"
        mode: EXCLUSIVE
        name: docker-node
        pullTimeout: 300
        stopTimeout: 1
credentials:
  system:
    domainCredentials:
      - credentials:
        - usernamePassword:
            username: ${GARMIN_CONNECT_USERNAME}
            password: ${GARMIN_CONNECT_PASSWORD}
            id: garmin-connect
            scope: GLOBAL
        - basicSSHUserPrivateKey:
            id: docker1-ssh
            privateKeySource:
              directEntry:
                privateKey: |
                  ${DOCKER1_SSH_PRIVATE_KEY}
            scope: GLOBAL
            username: jenkins
        - string:
            scope: GLOBAL
            id: update-jenkins-token
            secret: ${UPDATE_JENKINS_TOKEN}
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
unclassified:
  simple-theme-plugin:
    elements:
    - cssUrl:
        url: https://tobix.github.io/jenkins-neo2-theme/dist/neo-light.css
  location:
    adminAddress: jenkins@overlord.ddns.net
    url: ${JENKINS_URL}