jenkins:
  slaveAgentPort: 50000
  systemMessage: Overlord Jenkins
  numExecutors: 0
  quietPeriod: 0
  mode: EXCLUSIVE
  agentProtocols:
    - JNLP4-connect
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_USERNAME}
          password: ${JENKINS_PASSWORD}
  globalNodeProperties:
    - envVars:
        env:
          - key: JENKINS_IP
            value: ${JENKINS_IP}
  views:
    - all:
        name: All
    - list:
        columns:
          - status
          - weather
          - jobName
          - lastSuccess
          - lastFailure
          - lastDuration
          - buildButton
        includeRegex: .*Jenkins.*
        name: Jenkins Management
  clouds:
  - docker:
      containerCap: 1
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: unix:///var/run/docker.sock
        readTimeout: 60
      name: docker
      templates:
      - connector: attach
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: mfugate/jenkins-worker:latest
        labelString: "python3 chrome selenium docker"
        mode: EXCLUSIVE
        name: docker-node
        pullTimeout: 300
        stopTimeout: 1
credentials:
  system:
    domainCredentials:
      - credentials:
        - usernamePassword:
            username: ${GARMIN_CONNECT_USERNAME}
            password: ${GARMIN_CONNECT_PASSWORD}
            id: garmin-connect
            scope: GLOBAL
        - basicSSHUserPrivateKey:
            id: docker1-ssh
            privateKeySource:
              directEntry:
                privateKey: |
                  ${DOCKER1_SSH_PRIVATE_KEY}
            scope: GLOBAL
            username: jenkins
        - string:
            scope: GLOBAL
            id: update-jenkins-token
            secret: ${JENKINS_TRUENAS_DOCKER_UPDATE_TOKEN}
        - azure:
            azureEnvironmentName: Azure
            clientId: ${AZURE_CLIENT_ID}
            clientSecret: ${AZURE_CLIENT_SECRET}
            subscriptionId: ${AZURE_SUBSCRIPTION_ID}
            tenant: ${AZURE_TENANT}
            id: az-vault
            scope: GLOBAL
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
unclassified:
  azureKeyVault:
    keyVaultURL: ${AZ_VAULT_URL}
    credentialID: az-vault
  buildDiscarders:
    configuredBuildDiscarders:
      - jobBuildDiscarder
      - defaultBuildDiscarder:
          discarder:
            logRotator:
              numToKeepStr: "10"
  simple-theme-plugin:
    elements:
    - cssUrl:
        url: https://tobix.github.io/jenkins-neo2-theme/dist/neo-light.css
  location:
    adminAddress: ${JENKINS_ADMIN_EMAIL}
    url: http://${JENKINS_IP}:${JENKINS_PORT}