jenkins:
  slaveAgentPort: 50000
  systemMessage: Overlord Jenkins
  numExecutors: 1
  quietPeriod: 0
  mode: NORMAL
  agentProtocols:
    - JNLP4-connect
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS-USERNAME}
          password: ${JENKINS-PASSWORD}
  globalNodeProperties:
    - envVars:
        env:
          - key: DOCKER1_REMOTE_USER
            value: jenkins
          - key: HASS_CONFIG_DIR
            value: /docker/home-assistant
          - key: HASS_TEST_CONFIG_DIR
            value: /docker/home-assistant-test
          - key: JENKINS_SSH_KEY
            value: jenkins-ssh
  clouds:
  - docker:
      containerCap: 3
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: unix:///var/run/docker.sock
        readTimeout: 60
      name: docker
      templates:
      - connector: attach
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: mfugate/jenkins-worker:latest
        labelString: "python3 chrome selenium docker"
        mode: EXCLUSIVE
        pullStrategy: PULL_ALWAYS
        pullTimeout: 300
        stopTimeout: 1
      - connector: attach
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: mfugate/jenkins-agent:ansible
        labelString: ansible
        mode: EXCLUSIVE
        pullStrategy: PULL_ALWAYS
        pullTimeout: 300
        stopTimeout: 1
credentials:
  system:
    domainCredentials:
      - credentials:
        - basicSSHUserPrivateKey:
            id: jenkins-ssh
            privateKeySource:
              directEntry:
                privateKey: |
                  ${JENKINS_SSH_KEY}
            scope: GLOBAL
            username: jenkins
            description: Jenkins SSH Key
        - azure:
            azureEnvironmentName: Azure
            clientId: ${AZURE_CLIENT_ID}
            clientSecret: ${AZURE_CLIENT_SECRET}
            subscriptionId: ${AZURE_SUBSCRIPTION_ID}
            tenant: ${AZURE_TENANT}
            id: az-vault
            scope: GLOBAL
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
unclassified:
  azureKeyVault:
    keyVaultURL: ${AZ_VAULT_URL}
    credentialID: az-vault
  buildDiscarders:
    configuredBuildDiscarders:
      - jobBuildDiscarder
      - defaultBuildDiscarder:
          discarder:
            logRotator:
              numToKeepStr: "10"
  globalLibraries:
    libraries:
      - name: 'jenkins-shared-library'
        defaultVersion: 'main'
        implicit: true
        includeInChangesets: false
        retriever:
          modernSCM:
            scm:
              git:
                remote: https://github.com/mfugate1/jenkins.git
  location:
    adminAddress: ${JENKINS-ADMIN-EMAIL}
    url: http://${JENKINS-IP}:${JENKINS-PORT}
