reloadAzureKeyVaultCache()

if (params.updatedSecrets) {
    // Can't use join directly on the result from readJSON, but collect
    // converts it to a normal list that we can use join on
    String secrets = readJSON(text: params.updatedSecrets).collect{it}.join(',').replace('-', '_')

    build (
        job: 'Update-Home-Assistant-Config/main',
        wait: false,
        parameters: [
            string(name: 'updatedSecrets', value: secrets)
        ]
    )
} else {
    echo 'No secrets to update'
}