name: Build Jenkins Docker Image
on:
  push:
    branches:
      - main
    paths:
      - 'setup/docker/**'
      - '.github/workflows/**'
  workflow_dispatch:
jobs:
  docker-build:
    name: Build Jenkins Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: overlord-vault
          secrets: >
            DOCKERHUB-PASSWORD,
            DOCKERHUB-USERNAME,
            HASS-TOKEN,
            JENKINS-TRUENAS-DOCKER-UPDATE-TOKEN,
            OVERLORD-URL
        id: az
      - run: "curl -X POST -H 'Authorization: Bearer ${{ steps.az.outputs.HASS-TOKEN }}' -d '{\"entity_id\": \"input_select.jenkins_status\", \"option\": \"Building\"}' ${{ steps.az.outputs.OVERLORD-URL }}/api/services/input_select/select_option"
        continue-on-error: true
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ steps.az.outputs.DOCKERHUB-USERNAME }}
          password: ${{ steps.az.outputs.DOCKERHUB-PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: setup/docker
          push: true
          tags: mfugate/jenkins:latest
      - run: "curl -X POST -H 'Authorization: Bearer ${{ steps.az.outputs.HASS-TOKEN }}' -d '{\"entity_id\": \"input_select.jenkins_status\", \"option\": \"None\"}' ${{ steps.az.outputs.OVERLORD-URL }}/api/services/input_select/select_option"
        continue-on-error: true
      - run: "curl ${{ steps.az.outputs.OVERLORD-URL }}/jenkins-webhook-truenas?token=${{ steps.az.outputs.JENKINS-TRUENAS-DOCKER-UPDATE-TOKEN }} -X POST -d '{}'"