name: Build Jenkins Agent Images
on:
  push:
    branches:
      - main
    paths:
      - 'agent-images/**'
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
      DOCKERHUB-USERNAME: ${{ steps.az.outputs.DOCKERHUB-USERNAME }}
      DOCKERHUB-PASSWORD: ${{ steps.az.outputs.DOCKERHUB-PASSWORD }}
    steps:
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: overlord-vault
          secrets: >
            DOCKERHUB-PASSWORD,
            DOCKERHUB-USERNAME,
            HASS-TOKEN,
            OVERLORD-URL
        id: az
      - run: "curl -X POST -H 'Authorization: Bearer ${{ steps.az.outputs.HASS-TOKEN }}' -d '{\"entity_id\": \"input_boolean.building_jenkins_agent_images\"}' ${{ steps.az.outputs.OVERLORD-URL }}/api/services/input_boolean/turn_on"
        continue-on-error: true
      - uses: actions/checkout@v2
      - id: matrix
        run: echo "::set-output name=value::$(ls agent-images | jq -ncR '[inputs]')"

  build-images:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ needs.setup.outputs.DOCKERHUB-USERNAME }}
          password: ${{ needs.setup.outputs.DOCKERHUB-PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: agent-images/${{ matrix.value }}
          push: true
          tags: mfugate/jenkins-agent:${{ matrix.value }}

  post-build:
    needs: [build-images]
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: overlord-vault
          secrets: HASS-TOKEN, OVERLORD-URL
        id: az
      - run: "curl -X POST -H 'Authorization: Bearer ${{ steps.az.outputs.HASS-TOKEN }}' -d '{\"entity_id\": \"input_boolean.building_jenkins_agent_images\"}' ${{ steps.az.outputs.OVERLORD-URL }}/api/services/input_boolean/turn_off"
        continue-on-error: true
