name: Build Jenkins Docker Image
on:
  push:
    branches:
      - main
    paths:
      - 'setup/docker/**'
jobs:
  docker-build:
    name: Build Jenkins Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: setup/docker
          push: true
          tags: mfugate/jenkins:latest
      - run: "curl ${{ secrets.JENKINS_URL }}?token=${{ secrets.JENKINS_UPDATE_TOKEN }}"